// source: packages/web/src/components
//
// Descriptor index of every component. Astro/TSX rendering needs the Astro runtime, so the
// components themselves are not executed here:
// PROVISIONAL: Astro component rendering, Solid islands and CSS modules need the Astro runtime.

/// Rendering framework of a component file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Framework {
    /// `.astro` server component.
    Astro,
    /// `.tsx` Solid island.
    Solid,
    /// `.css` / `.module.css` stylesheet.
    Css,
}

/// One component file under `src/components`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Component {
    /// Path relative to `src/components`, e.g. `share/part.tsx`.
    pub file: &'static str,
    /// Rendering framework, from the file extension.
    pub framework: Framework,
    /// Line count of the source file.
    pub lines: usize,
    /// Top-level exported symbols (`export function|const|type|... Name`).
    pub exports: &'static [&'static str],
}

/// Every component file, in source-tree order.
pub const COMPONENTS: [Component; 28] = [
    Component {
        file: "Footer.astro",
        framework: Framework::Astro,
        lines: 126,
        exports: &[],
    },
    Component {
        file: "Head.astro",
        framework: Framework::Astro,
        lines: 55,
        exports: &[],
    },
    Component {
        file: "Header.astro",
        framework: Framework::Astro,
        lines: 137,
        exports: &[],
    },
    Component {
        file: "Hero.astro",
        framework: Framework::Astro,
        lines: 12,
        exports: &[],
    },
    Component {
        file: "Lander.astro",
        framework: Framework::Astro,
        lines: 722,
        exports: &[],
    },
    Component {
        file: "LanguageSelect.astro",
        framework: Framework::Astro,
        lines: 30,
        exports: &[],
    },
    Component {
        file: "Share.tsx",
        framework: Framework::Solid,
        lines: 647,
        exports: &["Share", "fromV1"],
    },
    Component {
        file: "SiteTitle.astro",
        framework: Framework::Astro,
        lines: 60,
        exports: &[],
    },
    Component {
        file: "icons/custom.tsx",
        framework: Framework::Solid,
        lines: 88,
        exports: &[
            "IconOpenAI",
            "IconAnthropic",
            "IconGemini",
            "IconOpencode",
            "IconMeta",
            "IconRobot",
            "IconBrain",
        ],
    },
    Component {
        file: "icons/index.tsx",
        framework: Framework::Solid,
        lines: 4455,
        exports: &[
            "IconAcademicCap",
            "IconAdjustmentsHorizontal",
            "IconAdjustmentsVertical",
            "IconArchiveBoxArrowDown",
            "IconArchiveBoxXMark",
            "IconArchiveBox",
            "IconArrowDownCircle",
            "IconArrowDownLeft",
            "IconArrowDownOnSquareStack",
            "IconArrowDownOnSquare",
            "IconArrowDownRight",
            "IconArrowDownTray",
            "IconArrowDown",
            "IconArrowLeftCircle",
            "IconArrowLeftOnRectangle",
            "IconArrowLeft",
            "IconArrowLongDown",
            "IconArrowLongLeft",
            "IconArrowLongRight",
            "IconArrowLongUp",
            "IconArrowPathRoundedSquare",
            "IconArrowPath",
            "IconArrowRightCircle",
            "IconArrowRightOnRectangle",
            "IconArrowRight",
            "IconArrowSmallDown",
            "IconArrowSmallLeft",
            "IconArrowSmallRight",
            "IconArrowSmallUp",
            "IconArrowTopRightOnSquare",
            "IconArrowTrendingDown",
            "IconArrowTrendingUp",
            "IconArrowUpCircle",
            "IconArrowUpLeft",
            "IconArrowUpOnSquareStack",
            "IconArrowUpOnSquare",
            "IconArrowUpRight",
            "IconArrowUpTray",
            "IconArrowUp",
            "IconArrowUturnDown",
            "IconArrowUturnLeft",
            "IconArrowUturnRight",
            "IconArrowUturnUp",
            "IconArrowsPointingIn",
            "IconArrowsPointingOut",
            "IconArrowsRightLeft",
            "IconArrowsUpDown",
            "IconAtSymbol",
            "IconBackspace",
            "IconBackward",
            "IconBanknotes",
            "IconBars2",
            "IconBars3BottomLeft",
            "IconBars3BottomRight",
            "IconBars3CenterLeft",
            "IconBars3",
            "IconBars4",
            "IconBarsArrowDown",
            "IconBarsArrowUp",
            "IconBattery0",
            "IconBattery100",
            "IconBattery50",
            "IconBeaker",
            "IconBellAlert",
            "IconBellSlash",
            "IconBellSnooze",
            "IconBell",
            "IconBoltSlash",
            "IconBolt",
            "IconBoltSolid",
            "IconBookOpen",
            "IconBookmarkSlash",
            "IconBookmarkSquare",
            "IconBookmark",
            "IconBriefcase",
            "IconBugAnt",
            "IconBuildingLibrary",
            "IconBuildingOffice2",
            "IconBuildingOffice",
            "IconBuildingStorefront",
            "IconCake",
            "IconCalculator",
            "IconCalendarDays",
            "IconCalendar",
            "IconCamera",
            "IconChartBarSquare",
            "IconChartBar",
            "IconChartPie",
            "IconChatBubbleBottomCenterText",
            "IconChatBubbleBottomCenter",
            "IconChatBubbleLeftEllipsis",
            "IconChatBubbleLeftRight",
            "IconChatBubbleLeft",
            "IconChatBubbleOvalLeftEllipsis",
            "IconChatBubbleOvalLeft",
            "IconCheckBadge",
            "IconCheckCircle",
            "IconCheck",
            "IconChevronDoubleDown",
            "IconChevronDoubleLeft",
            "IconChevronDoubleRight",
            "IconChevronDoubleUp",
            "IconChevronDown",
            "IconChevronLeft",
            "IconChevronRight",
            "IconChevronUpDown",
            "IconChevronUp",
            "IconCircleStack",
            "IconClipboardDocumentCheck",
            "IconClipboardDocumentList",
            "IconClipboardDocument",
            "IconClipboard",
            "IconClock",
            "IconCloudArrowDown",
            "IconCloudArrowUp",
            "IconCloud",
            "IconCodeBracketSquare",
            "IconCodeBracket",
            "IconCog6Tooth",
            "IconCog8Tooth",
            "IconCog",
            "IconCommandLine",
            "IconComputerDesktop",
            "IconCpuChip",
            "IconCreditCard",
            "IconCubeTransparent",
            "IconCube",
            "IconCurrencyBangladeshi",
            "IconCurrencyDollar",
            "IconCurrencyEuro",
            "IconCurrencyPound",
            "IconCurrencyRupee",
            "IconCurrencyYen",
            "IconCursorArrowRays",
            "IconCursorArrowRipple",
            "IconDevicePhoneMobile",
            "IconDeviceTablet",
            "IconDocumentArrowDown",
            "IconDocumentArrowUp",
            "IconDocumentChartBar",
            "IconDocumentCheck",
            "IconDocumentDuplicate",
            "IconDocumentMagnifyingGlass",
            "IconDocumentMinus",
            "IconDocumentPlus",
            "IconDocumentText",
            "IconDocument",
            "IconEllipsisHorizontalCircle",
            "IconEllipsisHorizontal",
            "IconEllipsisVertical",
            "IconEnvelopeOpen",
            "IconEnvelope",
            "IconEnvelopeSolid",
            "IconExclamationCircle",
            "IconExclamationTriangle",
            "IconEyeDropper",
            "IconEyeSlash",
            "IconEye",
            "IconFaceFrown",
            "IconFaceSmile",
            "IconFilm",
            "IconFingerPrint",
            "IconFire",
            "IconFlag",
            "IconFolderArrowDown",
            "IconFolderMinus",
            "IconFolderOpen",
            "IconFolderPlus",
            "IconFolder",
            "IconForward",
            "IconFunnel",
            "IconGif",
            "IconGiftTop",
            "IconGift",
            "IconGlobeAlt",
            "IconGlobeAmericas",
            "IconGlobeAsiaAustralia",
            "IconGlobeEuropeAfrica",
            "IconHandRaised",
            "IconHandThumbDown",
            "IconHandThumbUp",
            "IconHashtag",
            "IconHeart",
            "IconHomeModern",
            "IconHome",
            "IconIdentification",
            "IconInboxArrowDown",
            "IconInboxStack",
            "IconInbox",
            "IconInformationCircle",
            "IconKey",
            "IconLanguage",
            "IconLifebuoy",
            "IconLightBulb",
            "IconLink",
            "IconListBullet",
            "IconLockClosed",
            "IconLockOpen",
            "IconMagnifyingGlassCircle",
            "IconMagnifyingGlassMinus",
            "IconMagnifyingGlassPlus",
            "IconMagnifyingGlass",
            "IconMapPin",
            "IconMap",
            "IconMegaphone",
            "IconMicrophone",
            "IconMinusCircle",
            "IconMinusSmall",
            "IconMinus",
            "IconMoon",
            "IconMusicalNote",
            "IconNewspaper",
            "IconNoSymbol",
            "IconPaintBrush",
            "IconPaperAirplane",
            "IconPaperClip",
            "IconPauseCircle",
            "IconPause",
            "IconPencilSquare",
            "IconPencil",
            "IconPhoneArrowDownLeft",
            "IconPhoneArrowUpRight",
            "IconPhoneXMark",
            "IconPhone",
            "IconPhoto",
            "IconPlayCircle",
            "IconPlayPause",
            "IconPlay",
            "IconPlusCircle",
            "IconPlusSmall",
            "IconPlus",
            "IconPower",
            "IconPresentationChartBar",
            "IconPresentationChartLine",
            "IconPrinter",
            "IconPuzzlePiece",
            "IconQrCode",
            "IconQuestionMarkCircle",
            "IconQueueList",
            "IconRadio",
            "IconReceiptPercent",
            "IconReceiptRefund",
            "IconRectangleGroup",
            "IconRectangleStack",
            "IconRocketLaunch",
            "IconRss",
            "IconScale",
            "IconScissors",
            "IconServerStack",
            "IconServer",
            "IconShare",
            "IconShieldCheck",
            "IconShieldExclamation",
            "IconShoppingBag",
            "IconShoppingCart",
            "IconSignalSlash",
            "IconSignal",
            "IconSparkles",
            "IconSpeakerWave",
            "IconSpeakerXMark",
            "IconSquare2Stack",
            "IconSquare3Stack3d",
            "IconSquares2x2",
            "IconSquaresPlus",
            "IconStar",
            "IconStopCircle",
            "IconStop",
            "IconSun",
            "IconSwatch",
            "IconTableCells",
            "IconTag",
            "IconTicket",
            "IconTrash",
            "IconTrophy",
            "IconTruck",
            "IconTv",
            "IconUserCircle",
            "IconUserGroup",
            "IconUserMinus",
            "IconUserPlus",
            "IconUser",
            "IconUsers",
            "IconVariable",
            "IconVideoCameraSlash",
            "IconVideoCamera",
            "IconViewColumns",
            "IconViewfinderCircle",
            "IconWallet",
            "IconWifi",
            "IconWindow",
            "IconWrenchScrewdriver",
            "IconWrench",
            "IconXCircle",
            "IconXMark",
            "IconCommand",
            "IconLetter",
            "IconMultiSelect",
            "IconSettings",
            "IconSingleSelect",
        ],
    },
    Component {
        file: "share.module.css",
        framework: Framework::Css,
        lines: 833,
        exports: &[],
    },
    Component {
        file: "share/common.tsx",
        framework: Framework::Solid,
        lines: 129,
        exports: &[
            "ShareMessages",
            "ShareI18nProvider",
            "useShareMessages",
            "normalizeLocale",
            "formatNumber",
            "formatCurrency",
            "formatCount",
            "AnchorIcon",
            "createOverflow",
            "formatDuration",
        ],
    },
    Component {
        file: "share/content-bash.module.css",
        framework: Framework::Css,
        lines: 86,
        exports: &[],
    },
    Component {
        file: "share/content-bash.tsx",
        framework: Framework::Solid,
        lines: 68,
        exports: &["ContentBash"],
    },
    Component {
        file: "share/content-code.module.css",
        framework: Framework::Css,
        lines: 27,
        exports: &[],
    },
    Component {
        file: "share/content-code.tsx",
        framework: Framework::Solid,
        lines: 31,
        exports: &["ContentCode"],
    },
    Component {
        file: "share/content-diff.module.css",
        framework: Framework::Css,
        lines: 154,
        exports: &[],
    },
    Component {
        file: "share/content-diff.tsx",
        framework: Framework::Solid,
        lines: 241,
        exports: &["ContentDiff"],
    },
    Component {
        file: "share/content-error.module.css",
        framework: Framework::Css,
        lines: 65,
        exports: &[],
    },
    Component {
        file: "share/content-error.tsx",
        framework: Framework::Solid,
        lines: 26,
        exports: &["ContentError"],
    },
    Component {
        file: "share/content-markdown.module.css",
        framework: Framework::Css,
        lines: 155,
        exports: &[],
    },
    Component {
        file: "share/content-markdown.tsx",
        framework: Framework::Solid,
        lines: 75,
        exports: &["ContentMarkdown"],
    },
    Component {
        file: "share/content-text.module.css",
        framework: Framework::Css,
        lines: 64,
        exports: &[],
    },
    Component {
        file: "share/content-text.tsx",
        framework: Framework::Solid,
        lines: 39,
        exports: &["ContentText"],
    },
    Component {
        file: "share/copy-button.module.css",
        framework: Framework::Css,
        lines: 31,
        exports: &[],
    },
    Component {
        file: "share/copy-button.tsx",
        framework: Framework::Solid,
        lines: 37,
        exports: &["CopyButton"],
    },
    Component {
        file: "share/part.module.css",
        framework: Framework::Css,
        lines: 429,
        exports: &[],
    },
    Component {
        file: "share/part.tsx",
        framework: Framework::Solid,
        lines: 817,
        exports: &[
            "PartProps",
            "Part",
            "TodoWriteTool",
            "GrepTool",
            "ListTool",
            "WebFetchTool",
            "ReadTool",
            "WriteTool",
            "EditTool",
            "BashTool",
            "GlobTool",
            "Spacer",
            "FallbackTool",
            "ProviderIcon",
        ],
    },
];

/// Verbatim exported symbols of `src/components/Share.tsx`.
pub const SHARE_TSX_EXPORTS: [&str; 2] = ["Share", "fromV1"];

/// Verbatim exported symbols of `src/components/icons/custom.tsx`.
pub const ICONS_CUSTOM_TSX_EXPORTS: [&str; 7] = [
    "IconOpenAI",
    "IconAnthropic",
    "IconGemini",
    "IconOpencode",
    "IconMeta",
    "IconRobot",
    "IconBrain",
];

/// Verbatim exported symbols of `src/components/share/common.tsx`.
pub const SHARE_COMMON_TSX_EXPORTS: [&str; 10] = [
    "ShareMessages",
    "ShareI18nProvider",
    "useShareMessages",
    "normalizeLocale",
    "formatNumber",
    "formatCurrency",
    "formatCount",
    "AnchorIcon",
    "createOverflow",
    "formatDuration",
];

/// Verbatim exported symbols of `src/components/share/part.tsx`.
pub const SHARE_PART_TSX_EXPORTS: [&str; 14] = [
    "PartProps",
    "Part",
    "TodoWriteTool",
    "GrepTool",
    "ListTool",
    "WebFetchTool",
    "ReadTool",
    "WriteTool",
    "EditTool",
    "BashTool",
    "GlobTool",
    "Spacer",
    "FallbackTool",
    "ProviderIcon",
];

/// Verbatim exported symbols of `src/components/icons/index.tsx` (heroicon set).
pub const ICONS_INDEX_EXPORTS: [&str; 299] = [
    "IconAcademicCap",
    "IconAdjustmentsHorizontal",
    "IconAdjustmentsVertical",
    "IconArchiveBoxArrowDown",
    "IconArchiveBoxXMark",
    "IconArchiveBox",
    "IconArrowDownCircle",
    "IconArrowDownLeft",
    "IconArrowDownOnSquareStack",
    "IconArrowDownOnSquare",
    "IconArrowDownRight",
    "IconArrowDownTray",
    "IconArrowDown",
    "IconArrowLeftCircle",
    "IconArrowLeftOnRectangle",
    "IconArrowLeft",
    "IconArrowLongDown",
    "IconArrowLongLeft",
    "IconArrowLongRight",
    "IconArrowLongUp",
    "IconArrowPathRoundedSquare",
    "IconArrowPath",
    "IconArrowRightCircle",
    "IconArrowRightOnRectangle",
    "IconArrowRight",
    "IconArrowSmallDown",
    "IconArrowSmallLeft",
    "IconArrowSmallRight",
    "IconArrowSmallUp",
    "IconArrowTopRightOnSquare",
    "IconArrowTrendingDown",
    "IconArrowTrendingUp",
    "IconArrowUpCircle",
    "IconArrowUpLeft",
    "IconArrowUpOnSquareStack",
    "IconArrowUpOnSquare",
    "IconArrowUpRight",
    "IconArrowUpTray",
    "IconArrowUp",
    "IconArrowUturnDown",
    "IconArrowUturnLeft",
    "IconArrowUturnRight",
    "IconArrowUturnUp",
    "IconArrowsPointingIn",
    "IconArrowsPointingOut",
    "IconArrowsRightLeft",
    "IconArrowsUpDown",
    "IconAtSymbol",
    "IconBackspace",
    "IconBackward",
    "IconBanknotes",
    "IconBars2",
    "IconBars3BottomLeft",
    "IconBars3BottomRight",
    "IconBars3CenterLeft",
    "IconBars3",
    "IconBars4",
    "IconBarsArrowDown",
    "IconBarsArrowUp",
    "IconBattery0",
    "IconBattery100",
    "IconBattery50",
    "IconBeaker",
    "IconBellAlert",
    "IconBellSlash",
    "IconBellSnooze",
    "IconBell",
    "IconBoltSlash",
    "IconBolt",
    "IconBoltSolid",
    "IconBookOpen",
    "IconBookmarkSlash",
    "IconBookmarkSquare",
    "IconBookmark",
    "IconBriefcase",
    "IconBugAnt",
    "IconBuildingLibrary",
    "IconBuildingOffice2",
    "IconBuildingOffice",
    "IconBuildingStorefront",
    "IconCake",
    "IconCalculator",
    "IconCalendarDays",
    "IconCalendar",
    "IconCamera",
    "IconChartBarSquare",
    "IconChartBar",
    "IconChartPie",
    "IconChatBubbleBottomCenterText",
    "IconChatBubbleBottomCenter",
    "IconChatBubbleLeftEllipsis",
    "IconChatBubbleLeftRight",
    "IconChatBubbleLeft",
    "IconChatBubbleOvalLeftEllipsis",
    "IconChatBubbleOvalLeft",
    "IconCheckBadge",
    "IconCheckCircle",
    "IconCheck",
    "IconChevronDoubleDown",
    "IconChevronDoubleLeft",
    "IconChevronDoubleRight",
    "IconChevronDoubleUp",
    "IconChevronDown",
    "IconChevronLeft",
    "IconChevronRight",
    "IconChevronUpDown",
    "IconChevronUp",
    "IconCircleStack",
    "IconClipboardDocumentCheck",
    "IconClipboardDocumentList",
    "IconClipboardDocument",
    "IconClipboard",
    "IconClock",
    "IconCloudArrowDown",
    "IconCloudArrowUp",
    "IconCloud",
    "IconCodeBracketSquare",
    "IconCodeBracket",
    "IconCog6Tooth",
    "IconCog8Tooth",
    "IconCog",
    "IconCommandLine",
    "IconComputerDesktop",
    "IconCpuChip",
    "IconCreditCard",
    "IconCubeTransparent",
    "IconCube",
    "IconCurrencyBangladeshi",
    "IconCurrencyDollar",
    "IconCurrencyEuro",
    "IconCurrencyPound",
    "IconCurrencyRupee",
    "IconCurrencyYen",
    "IconCursorArrowRays",
    "IconCursorArrowRipple",
    "IconDevicePhoneMobile",
    "IconDeviceTablet",
    "IconDocumentArrowDown",
    "IconDocumentArrowUp",
    "IconDocumentChartBar",
    "IconDocumentCheck",
    "IconDocumentDuplicate",
    "IconDocumentMagnifyingGlass",
    "IconDocumentMinus",
    "IconDocumentPlus",
    "IconDocumentText",
    "IconDocument",
    "IconEllipsisHorizontalCircle",
    "IconEllipsisHorizontal",
    "IconEllipsisVertical",
    "IconEnvelopeOpen",
    "IconEnvelope",
    "IconEnvelopeSolid",
    "IconExclamationCircle",
    "IconExclamationTriangle",
    "IconEyeDropper",
    "IconEyeSlash",
    "IconEye",
    "IconFaceFrown",
    "IconFaceSmile",
    "IconFilm",
    "IconFingerPrint",
    "IconFire",
    "IconFlag",
    "IconFolderArrowDown",
    "IconFolderMinus",
    "IconFolderOpen",
    "IconFolderPlus",
    "IconFolder",
    "IconForward",
    "IconFunnel",
    "IconGif",
    "IconGiftTop",
    "IconGift",
    "IconGlobeAlt",
    "IconGlobeAmericas",
    "IconGlobeAsiaAustralia",
    "IconGlobeEuropeAfrica",
    "IconHandRaised",
    "IconHandThumbDown",
    "IconHandThumbUp",
    "IconHashtag",
    "IconHeart",
    "IconHomeModern",
    "IconHome",
    "IconIdentification",
    "IconInboxArrowDown",
    "IconInboxStack",
    "IconInbox",
    "IconInformationCircle",
    "IconKey",
    "IconLanguage",
    "IconLifebuoy",
    "IconLightBulb",
    "IconLink",
    "IconListBullet",
    "IconLockClosed",
    "IconLockOpen",
    "IconMagnifyingGlassCircle",
    "IconMagnifyingGlassMinus",
    "IconMagnifyingGlassPlus",
    "IconMagnifyingGlass",
    "IconMapPin",
    "IconMap",
    "IconMegaphone",
    "IconMicrophone",
    "IconMinusCircle",
    "IconMinusSmall",
    "IconMinus",
    "IconMoon",
    "IconMusicalNote",
    "IconNewspaper",
    "IconNoSymbol",
    "IconPaintBrush",
    "IconPaperAirplane",
    "IconPaperClip",
    "IconPauseCircle",
    "IconPause",
    "IconPencilSquare",
    "IconPencil",
    "IconPhoneArrowDownLeft",
    "IconPhoneArrowUpRight",
    "IconPhoneXMark",
    "IconPhone",
    "IconPhoto",
    "IconPlayCircle",
    "IconPlayPause",
    "IconPlay",
    "IconPlusCircle",
    "IconPlusSmall",
    "IconPlus",
    "IconPower",
    "IconPresentationChartBar",
    "IconPresentationChartLine",
    "IconPrinter",
    "IconPuzzlePiece",
    "IconQrCode",
    "IconQuestionMarkCircle",
    "IconQueueList",
    "IconRadio",
    "IconReceiptPercent",
    "IconReceiptRefund",
    "IconRectangleGroup",
    "IconRectangleStack",
    "IconRocketLaunch",
    "IconRss",
    "IconScale",
    "IconScissors",
    "IconServerStack",
    "IconServer",
    "IconShare",
    "IconShieldCheck",
    "IconShieldExclamation",
    "IconShoppingBag",
    "IconShoppingCart",
    "IconSignalSlash",
    "IconSignal",
    "IconSparkles",
    "IconSpeakerWave",
    "IconSpeakerXMark",
    "IconSquare2Stack",
    "IconSquare3Stack3d",
    "IconSquares2x2",
    "IconSquaresPlus",
    "IconStar",
    "IconStopCircle",
    "IconStop",
    "IconSun",
    "IconSwatch",
    "IconTableCells",
    "IconTag",
    "IconTicket",
    "IconTrash",
    "IconTrophy",
    "IconTruck",
    "IconTv",
    "IconUserCircle",
    "IconUserGroup",
    "IconUserMinus",
    "IconUserPlus",
    "IconUser",
    "IconUsers",
    "IconVariable",
    "IconVideoCameraSlash",
    "IconVideoCamera",
    "IconViewColumns",
    "IconViewfinderCircle",
    "IconWallet",
    "IconWifi",
    "IconWindow",
    "IconWrenchScrewdriver",
    "IconWrench",
    "IconXCircle",
    "IconXMark",
    "IconCommand",
    "IconLetter",
    "IconMultiSelect",
    "IconSettings",
    "IconSingleSelect",
];

/// Starlight component overrides wired in `astro.config.mjs`, with their source files.
pub const STARLIGHT_OVERRIDES: [(&str, &str); 6] = [
    ("Hero", "./src/components/Hero.astro"),
    ("Head", "./src/components/Head.astro"),
    ("Header", "./src/components/Header.astro"),
    ("Footer", "./src/components/Footer.astro"),
    ("LanguageSelect", "./src/components/LanguageSelect.astro"),
    ("SiteTitle", "./src/components/SiteTitle.astro"),
];

/// Look up a component by its path relative to `src/components`.
pub fn find(file: &str) -> Option<&'static Component> {
    COMPONENTS.iter().find(|component| component.file == file)
}

/// Number of exported symbols across every TSX module.
pub const TOTAL_EXPORTS: usize = 339;
