[workspace]
members = [
    "crates/app",
    "crates/cli",
    "crates/client",
    "crates/codemode",
    "crates/containers",
    "crates/core",
    "crates/effect-drizzle-sqlite",
    "crates/effect-sqlite-node",
    "crates/function",
    "crates/httpapi-codegen",
    "crates/http-recorder",
    "crates/llm",
    "crates/opencode",
    "crates/protocol",
    "crates/plugin",
    "crates/schema",
    "crates/sdk",
    "crates/script",
    "crates/server",
    "crates/slack",
    "crates/sdk-next",
    "crates/tui",
    "crates/docs",
    "crates/enterprise",
    "crates/identity",
    "crates/storybook",
    "crates/stats",
    "crates/web",
]
resolver = "2"

[workspace.package]
version = "1.18.30"
edition = "2021"
license = "MIT"
