// source: src/effect/app-runtime.ts — exports: AppLayer, AppServices,
// AppRuntime (48-node group verbatim order + Ripgrep merge + Observability;
// runSync/runPromise/runPromiseExit/runFork/runCallback/dispose surface).

/// source: AppLayer group — verbatim node order (48 entries).
pub const APP_NODES: &[&str] = &[
    "@opencode-ai/core/npm.Npm",
    "@opencode-ai/core/fs-util.FSUtil",
    "@opencode-ai/core/database/database.Database",
    "@/auth.Auth",
    "@/account/account.Account",
    "@/config/config.Config",
    "@/git.Git",
    "@/storage/storage.Storage",
    "@/snapshot.Snapshot",
    "@/plugin.Plugin",
    "@opencode-ai/core/models-dev.ModelsDev",
    "@/provider/provider.Provider",
    "@/provider/auth.ProviderAuth",
    "@/agent/agent.Agent",
    "@/skill.Skill",
    "@/skill/discovery.Discovery",
    "@/question.Question",
    "@/permission.Permission",
    "@/session/todo.Todo",
    "@/session/session.Session",
    "@opencode-ai/core/session/projector.SessionProjector",
    "@/session/status.SessionStatus",
    "@/background/job.BackgroundJob",
    "@/effect/runtime-flags.RuntimeFlags",
    "@/event-v2-bridge.EventV2Bridge",
    "@/session/run-state.SessionRunState",
    "@/session/processor.SessionProcessor",
    "@/session/compaction.SessionCompaction",
    "@/session/revert.SessionRevert",
    "@/session/summary.SessionSummary",
    "@/session/prompt.SessionPrompt",
    "@/session/instruction.Instruction",
    "@/session/llm.LLM",
    "@/lsp/lsp.LSP",
    "@/mcp.MCP",
    "@/mcp/auth.McpAuth",
    "@/command.Command",
    "@/tool/truncate.Truncate",
    "@/tool/registry.ToolRegistry",
    "@/format.Format",
    "@/project/instance-store.InstanceStore",
    "@/project/project.Project",
    "@/project/vcs.Vcs",
    "@/control-plane/workspace.Workspace",
    "@/worktree.Worktree",
    "@/installation.Installation",
    "@/share/share-next.ShareNext",
    "@/share/session.SessionShare",
];

/// source: AppRuntime surface — verbatim method order.
pub const APP_RUNTIME_METHODS: &[&str] = &[
    "runSync",
    "runPromise",
    "runPromiseExit",
    "runFork",
    "runCallback",
    "dispose",
];
